# Generated by Django 6.0.4 on 2026-05-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_aboutpage_subic_sunrise_aboutpage_subic_sunrise_b_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutpage",
            old_name="subic_sunrise",
            new_name="about_bottom",
        ),
        migrations.RenameField(
            model_name="aboutpage",
            old_name="subic_sunrise_b",
            new_name="about_left",
        ),
        migrations.RenameField(
            model_name="aboutpage",
            old_name="z_camara_crop",
            new_name="about_right",
        ),
    ]
