# Generated by Django 5.2.16 on 2026-07-11 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_subic_sunrise_aboutpage_about_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopage',
            name='date_taken',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
