# Generated by Django 5.2.16 on 2026-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_photopage_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopage',
            name='category',
            field=models.CharField(blank=True, choices=[('sea_surf', 'sea & surf'), ('flora', 'flora'), ('streets_fiestas', 'streets & fiestas'), ('golden_hour', 'golden hour'), ('nature', 'nature')], max_length=20),
        ),
    ]
