# Generated by Django 5.2.12 on 2026-03-31 08:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_atelierpage_blogpage_musingspage_techpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='techpostpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='GalleryPage',
        ),
        migrations.DeleteModel(
            name='SectionPage',
        ),
    ]
