# Generated by Django 5.2.12 on 2026-03-31 09:02

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_sectionpage_page_ptr_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='techpostpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
