# Generated by Django 5.2.12 on 2026-04-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogpage_date_blogpage_main_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechPostPage',
        ),
    ]
